
const AUTH_API_BASE = "/api/auth";
const AUTH_STATE_ENDPOINT = `${AUTH_API_BASE}/state`;
const AUTH_SUPABASE_CONFIG_ENDPOINT = `${AUTH_API_BASE}/supabase-config`;
const AUTH_USERS_ENDPOINT = `${AUTH_API_BASE}/users`;
const AUTH_INVITE_ENDPOINT = `${AUTH_API_BASE}/invite`;
const AUTH_INVITE_CANCEL_ENDPOINT = `${AUTH_API_BASE}/invite/cancel`;
const AUTH_USER_REVOKE_ENDPOINT = `${AUTH_API_BASE}/users/revoke`;

export {
  AUTH_STATE_ENDPOINT,
  AUTH_SUPABASE_CONFIG_ENDPOINT,
  AUTH_INVITE_CANCEL_ENDPOINT,
  AUTH_INVITE_ENDPOINT,
  AUTH_USER_REVOKE_ENDPOINT,
  AUTH_USERS_ENDPOINT
};
