const LARAVEL_DATABASE_RUNTIME_CONFIG = "laravel_database_runtime";
const LARAVEL_PROJECT_KNOWLEDGE_RELATIVE_PATH = ".vibe64/LARAVEL_PROJECT.md";

export {
  LARAVEL_DATABASE_RUNTIME_CONFIG,
  LARAVEL_PROJECT_KNOWLEDGE_RELATIVE_PATH
};
