import assert from "node:assert/strict";
import { exec as execCallback } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";

import {
  DEFAULT_CODE_INDEX_RELATIVE_PATH,
  javascriptAdapterCodeIndexCommand,
  javascriptCodeIndexCommand,
  packageManagerScriptCommand,
  phpCodeIndexCommand
} from "@local/ai-studio-adapters/server/codeIndexCommands";
import { withTemporaryRoot } from "./aiStudioTestHelpers.js";

const exec = promisify(execCallback);

async function writeProjectFile(root, relativePath, text) {
  const filePath = path.join(root, relativePath);
  await mkdir(path.dirname(filePath), {
    recursive: true
  });
  await writeFile(filePath, text, "utf8");
}

async function runShellCommand(command, cwd) {
  await exec(command, {
    cwd,
    maxBuffer: 1024 * 1024,
    shell: "/bin/bash"
  });
}

test("code-index fallback commands wrap script assets as explicit heredocs", () => {
  const javascriptCommand = javascriptCodeIndexCommand({
    outputPath: "var/index.md"
  });
  const phpCommand = phpCodeIndexCommand({
    outputPath: "var/php-index.md"
  });

  assert.match(javascriptCommand, /^AI_STUDIO_CODE_INDEX_PATH=var\/index\.md node --input-type=module <<'AI_STUDIO_JS_CODE_INDEX'/u);
  assert.match(javascriptCommand, /Generated by the AI Studio JavaScript adapter\./u);
  assert.match(javascriptCommand, /\nAI_STUDIO_JS_CODE_INDEX$/u);
  assert.doesNotMatch(javascriptCommand, /String\.raw/u);

  assert.match(phpCommand, /^AI_STUDIO_CODE_INDEX_PATH=var\/php-index\.md php <<'AI_STUDIO_PHP_CODE_INDEX'/u);
  assert.match(phpCommand, /Generated by the AI Studio Laravel\/PHP adapter\./u);
  assert.match(phpCommand, /\nAI_STUDIO_PHP_CODE_INDEX$/u);
  assert.doesNotMatch(phpCommand, /String\.raw/u);
});

test("javascript code-index fallback command writes deterministic declaration markdown", async () => {
  await withTemporaryRoot(async (targetRoot) => {
    await Promise.all([
      writeProjectFile(targetRoot, "src/alpha.js", [
        "export function alpha() {}",
        "export const beta = () => {};",
        "class Internal {}",
        ""
      ].join("\n")),
      writeProjectFile(targetRoot, "src/second.ts", [
        "export async function gamma() {}",
        "const delta = async () => {};",
        ""
      ].join("\n")),
      writeProjectFile(targetRoot, "node_modules/ignored.js", "export function ignored() {}\n"),
      writeProjectFile(targetRoot, "dist/ignored.js", "export function ignoredDist() {}\n")
    ]);

    await runShellCommand(javascriptCodeIndexCommand(), targetRoot);

    const codeIndex = await readFile(path.join(targetRoot, DEFAULT_CODE_INDEX_RELATIVE_PATH), "utf8");
    assert.match(codeIndex, /^# AI Studio Code Index\n\nGenerated by the AI Studio JavaScript adapter\.\n\n## Files\n/u);
    assert.match(codeIndex, /### src\/alpha\.js\n- line 1: function alpha\n- line 2: function beta\n- line 3: class Internal/u);
    assert.match(codeIndex, /### src\/second\.ts\n- line 1: function gamma\n- line 2: function delta/u);
    assert.doesNotMatch(codeIndex, /ignored/u);
  });
});

test("package-manager code-index command uses the project script when it exists", () => {
  assert.equal(
    packageManagerScriptCommand({
      packageJson: {
        scripts: {
          "ai-studio:index": "custom-index"
        }
      },
      packageManager: "pnpm",
      scriptName: "ai-studio:index"
    }),
    "corepack pnpm run ai-studio:index"
  );
  assert.equal(
    packageManagerScriptCommand({
      packageJson: {
        scripts: {}
      },
      packageManager: "npm",
      scriptName: "ai-studio:index"
    }),
    ""
  );
});

test("javascript adapter code-index command centralizes package script fallback metadata", () => {
  const packageScriptIndex = javascriptAdapterCodeIndexCommand({
    packageJson: {
      scripts: {
        "ai-studio:index": "custom-index"
      }
    },
    packageManager: {
      name: "pnpm"
    }
  });
  assert.equal(packageScriptIndex.command, "corepack pnpm run ai-studio:index");
  assert.equal(packageScriptIndex.commandPreview, "corepack pnpm run ai-studio:index");
  assert.deepEqual(packageScriptIndex.metadata, {
    code_index_command_source: "package-script",
    code_index_package_manager: "pnpm",
    code_index_path: DEFAULT_CODE_INDEX_RELATIVE_PATH
  });

  const fallbackIndex = javascriptAdapterCodeIndexCommand({
    packageJson: {},
    packageManager: "npm"
  });
  assert.equal(
    fallbackIndex.commandPreview,
    `node --input-type=module # writes ${DEFAULT_CODE_INDEX_RELATIVE_PATH}`
  );
  assert.equal(fallbackIndex.metadata.code_index_command_source, "javascript-indexer");
  assert.match(fallbackIndex.command, /^AI_STUDIO_CODE_INDEX_PATH=.* node --input-type=module/u);
});
