const PREVIEW_BRIDGE_VERSION = 1;
const PREVIEW_LOCATION_MESSAGE_TYPE = "vibe64:preview-location";
const PREVIEW_QUERY_MESSAGE_TYPE = "vibe64:preview-query";
const PREVIEW_PROXY_TOKEN_QUERY_PARAM = "vibe64_preview_token";

export {
  PREVIEW_BRIDGE_VERSION,
  PREVIEW_LOCATION_MESSAGE_TYPE,
  PREVIEW_PROXY_TOKEN_QUERY_PARAM,
  PREVIEW_QUERY_MESSAGE_TYPE
};
