const PREVIEW_BRIDGE_VERSION = 3;
const PREVIEW_DIAGNOSTICS_REQUEST_MESSAGE_TYPE = "vibe64:preview-diagnostics-request";
const PREVIEW_DIAGNOSTICS_RESPONSE_MESSAGE_TYPE = "vibe64:preview-diagnostics-response";
const PREVIEW_IDENTITY_REQUEST_MESSAGE_TYPE = "vibe64:preview-identity-request";
const PREVIEW_IDENTITY_RESPONSE_MESSAGE_TYPE = "vibe64:preview-identity-response";
const PREVIEW_LOCATION_MESSAGE_TYPE = "vibe64:preview-location";
const PREVIEW_QUERY_MESSAGE_TYPE = "vibe64:preview-query";
const PREVIEW_PROXY_TOKEN_QUERY_PARAM = "vibe64_preview_token";

export {
  PREVIEW_BRIDGE_VERSION,
  PREVIEW_DIAGNOSTICS_REQUEST_MESSAGE_TYPE,
  PREVIEW_DIAGNOSTICS_RESPONSE_MESSAGE_TYPE,
  PREVIEW_IDENTITY_REQUEST_MESSAGE_TYPE,
  PREVIEW_IDENTITY_RESPONSE_MESSAGE_TYPE,
  PREVIEW_LOCATION_MESSAGE_TYPE,
  PREVIEW_PROXY_TOKEN_QUERY_PARAM,
  PREVIEW_QUERY_MESSAGE_TYPE
};
