import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const outputPath = process.env.VIBE64_CODE_INDEX_PATH || ".vibe64/code-index.md";
const codeExtensions = new Set([".cjs", ".js", ".jsx", ".mjs", ".ts", ".tsx", ".vue"]);
const excludedDirs = new Set([
  ".git",
  ".vibe64",
  ".next",
  ".nuxt",
  ".output",
  ".turbo",
  "build",
  "coverage",
  "dist",
  "node_modules"
]);

function markdownPath(filePath) {
  return filePath.split(path.sep).join("/");
}

async function walk(currentDir, relativeRoot = "") {
  const entries = await readdir(currentDir, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (excludedDirs.has(entry.name)) {
      continue;
    }
    const absolutePath = path.join(currentDir, entry.name);
    const relativePath = relativeRoot ? path.join(relativeRoot, entry.name) : entry.name;
    if (entry.isDirectory()) {
      files.push(...await walk(absolutePath, relativePath));
      continue;
    }
    if (entry.isFile() && codeExtensions.has(path.extname(entry.name))) {
      files.push({
        absolutePath,
        relativePath: markdownPath(relativePath)
      });
    }
  }
  return files;
}

function lineNumber(source, index) {
  return source.slice(0, index).split("\n").length;
}

function collectDeclarations(source) {
  const declarations = [];
  const patterns = [
    {
      kind: "function",
      pattern: /^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/gmu
    },
    {
      kind: "function",
      pattern: /^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>/gmu
    },
    {
      kind: "function",
      pattern: /^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?function\b/gmu
    },
    {
      kind: "class",
      pattern: /^\s*(?:export\s+)?(?:default\s+)?class\s+([A-Za-z_$][\w$]*)\b/gmu
    }
  ];
  for (const { kind, pattern } of patterns) {
    for (const match of source.matchAll(pattern)) {
      declarations.push({
        kind,
        line: lineNumber(source, match.index || 0),
        name: match[1] || ""
      });
    }
  }
  return declarations
    .filter((entry) => entry.name)
    .sort((left, right) => left.line - right.line || left.name.localeCompare(right.name));
}

const files = await walk(root);
const lines = [
  "# Vibe64 Code Index",
  "",
  "Generated by the Vibe64 JavaScript adapter.",
  "",
  "## Files"
];
let declarationCount = 0;

for (const file of files) {
  const source = await readFile(file.absolutePath, "utf8");
  const declarations = collectDeclarations(source);
  if (declarations.length === 0) {
    continue;
  }
  declarationCount += declarations.length;
  lines.push("", "### " + file.relativePath);
  for (const declaration of declarations) {
    lines.push("- line " + declaration.line + ": " + declaration.kind + " " + declaration.name);
  }
}

if (declarationCount === 0) {
  lines.push("", "No JavaScript, TypeScript, or Vue declarations were detected.");
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, lines.join("\n") + "\n", "utf8");
console.log("Wrote " + outputPath);
