import {
  VIBE64_APP_ROOT_ENV,
  VIBE64_TARGET_ROOT_ENV
} from "@local/vibe64-core/server/studioRoots";

const VIBE64_RUNTIME_NAME = "vibe64";

const VIBE64_BYPASS_LOCALHOST_CHECK_ENV = "VIBE64_BYPASS_LOCALHOST_CHECK";
const VIBE64_SKIP_STALE_TERMINAL_CLEANUP_ENV = "VIBE64_SKIP_STALE_TERMINAL_CLEANUP";
const STUDIO_BASE_TOOLCHAIN_IMAGE = `${VIBE64_RUNTIME_NAME}-base-toolchain:0.1.0`;
const STUDIO_PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright";
const STUDIO_PLAYWRIGHT_BROWSERS_VOLUME = "vibe64_playwright_browsers";
const STUDIO_TOOL_HOME_VOLUME = "vibe64_tool_home";
const STUDIO_TOOL_HOME_PATH = "/home/vibe64";
const STUDIO_TOOL_HOME_NPM_PREFIX = `${STUDIO_TOOL_HOME_PATH}/.local`;
const STUDIO_TOOL_HOME_BIN_PATH = `${STUDIO_TOOL_HOME_NPM_PREFIX}/bin`;
const STUDIO_TEMP_DIR_NAME = VIBE64_RUNTIME_NAME;

const STUDIO_DOCKER_LABEL_PREFIX = VIBE64_RUNTIME_NAME;
const STUDIO_DAEMON_PID_LABEL = `${STUDIO_DOCKER_LABEL_PREFIX}.daemon-pid`;

const STUDIO_HOST_UID_ENV = "VIBE64_HOST_UID";
const STUDIO_HOST_GID_ENV = "VIBE64_HOST_GID";

const STUDIO_CODEX_CONTAINER_PREFIX = `${VIBE64_RUNTIME_NAME}-codex`;

function studioDockerLabel(name = "", value = undefined) {
  const key = `${STUDIO_DOCKER_LABEL_PREFIX}.${String(name || "").trim()}`;
  return value === undefined ? key : `${key}=${String(value)}`;
}

export {
  VIBE64_APP_ROOT_ENV,
  VIBE64_BYPASS_LOCALHOST_CHECK_ENV,
  VIBE64_RUNTIME_NAME,
  VIBE64_SKIP_STALE_TERMINAL_CLEANUP_ENV,
  VIBE64_TARGET_ROOT_ENV,
  STUDIO_CODEX_CONTAINER_PREFIX,
  STUDIO_BASE_TOOLCHAIN_IMAGE,
  STUDIO_DAEMON_PID_LABEL,
  STUDIO_HOST_GID_ENV,
  STUDIO_HOST_UID_ENV,
  STUDIO_PLAYWRIGHT_BROWSERS_PATH,
  STUDIO_PLAYWRIGHT_BROWSERS_VOLUME,
  STUDIO_TOOL_HOME_BIN_PATH,
  STUDIO_TOOL_HOME_NPM_PREFIX,
  STUDIO_TOOL_HOME_PATH,
  STUDIO_TEMP_DIR_NAME,
  STUDIO_TOOL_HOME_VOLUME,
  studioDockerLabel
};
