const NEXTJS_DATABASE_RUNTIME_CONFIG = "nextjs_database_runtime";
const NEXTJS_DATA_LAYER_CONFIG = "nextjs_data_layer";
const NEXTJS_PACKAGE_MANAGER_CONFIG = "nextjs_package_manager";
const NEXTJS_PROJECT_KNOWLEDGE_RELATIVE_PATH = ".vibe64/project-knowledge/nextjs.md";
const NEXTJS_SEED_BUNDLER_CONFIG = "nextjs_seed_bundler";
const NEXTJS_SEED_IMPORT_ALIAS_CONFIG = "nextjs_seed_import_alias";
const NEXTJS_SEED_LANGUAGE_CONFIG = "nextjs_seed_language";
const NEXTJS_SEED_LINTER_CONFIG = "nextjs_seed_linter";
const NEXTJS_SEED_SOURCE_LAYOUT_CONFIG = "nextjs_seed_source_layout";
const NEXTJS_SEED_STYLING_CONFIG = "nextjs_seed_styling";

export {
  NEXTJS_DATABASE_RUNTIME_CONFIG,
  NEXTJS_DATA_LAYER_CONFIG,
  NEXTJS_PACKAGE_MANAGER_CONFIG,
  NEXTJS_PROJECT_KNOWLEDGE_RELATIVE_PATH,
  NEXTJS_SEED_BUNDLER_CONFIG,
  NEXTJS_SEED_IMPORT_ALIAS_CONFIG,
  NEXTJS_SEED_LANGUAGE_CONFIG,
  NEXTJS_SEED_LINTER_CONFIG,
  NEXTJS_SEED_SOURCE_LAYOUT_CONFIG,
  NEXTJS_SEED_STYLING_CONFIG
};
