import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  isMissingPathError,
  isPlainObject,
  normalizeText,
  pathExists,
  vibe64Error
} from "./core.js";

const RUNTIME_CONFIG_OWNERS = Object.freeze({
  ADAPTER: "adapter",
  USER: "user",
  VIBE64: "vibe64"
});
const RUNTIME_CONFIG_SCOPES = Object.freeze({
  DEV: "dev",
  PROD: "prod"
});
const RUNTIME_CONFIG_PHASES = Object.freeze({
  CLIENT_BUILD: "client-build",
  DEPLOY: "deploy",
  GENERATE: "generate",
  INSTALL: "install",
  MIGRATE: "migrate",
  PREVIEW: "preview",
  SEED: "seed",
  SERVER: "server"
});
const RUNTIME_CONFIG_OWNER_VALUES = new Set(Object.values(RUNTIME_CONFIG_OWNERS));
const RUNTIME_CONFIG_SCOPE_VALUES = new Set(Object.values(RUNTIME_CONFIG_SCOPES));
const RUNTIME_CONFIG_PHASE_VALUES = new Set(Object.values(RUNTIME_CONFIG_PHASES));
const RUNTIME_CONFIG_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/u;
const RUNTIME_CONFIG_SECRET_KEY_PATTERN = /(PASSWORD|PASS|TOKEN|SECRET|KEY|CREDENTIAL|PWD|DATABASE_URL|DSN)/iu;
const RUNTIME_CONFIG_DOTENV_FORMAT = "dotenv";
const VIBE64_GENERATED_ENV_HEADER_LINES = Object.freeze([
  "# Generated by Vibe64.",
  "# Do not edit. Changes will be overwritten.",
  "# Configure user-owned values in Vibe64 Runtime Config."
]);
const VIBE64_GENERATED_ENV_HEADER = `${VIBE64_GENERATED_ENV_HEADER_LINES.join("\n")}\n`;
const REDACTED_RUNTIME_CONFIG_VALUE = "********";

function runtimeConfigError(message, code) {
  return vibe64Error(message, code);
}

function normalizeRuntimeConfigKey(key = "") {
  const normalizedKey = normalizeText(key);
  if (!RUNTIME_CONFIG_KEY_PATTERN.test(normalizedKey)) {
    throw runtimeConfigError(
      `Invalid runtime config key: ${normalizedKey || "(empty)"}`,
      "vibe64_runtime_config_key_invalid"
    );
  }
  return normalizedKey;
}

function normalizeRuntimeConfigOwner(owner = RUNTIME_CONFIG_OWNERS.USER) {
  const normalizedOwner = normalizeText(owner || RUNTIME_CONFIG_OWNERS.USER);
  if (!RUNTIME_CONFIG_OWNER_VALUES.has(normalizedOwner)) {
    throw runtimeConfigError(
      `Invalid runtime config owner: ${normalizedOwner || "(empty)"}`,
      "vibe64_runtime_config_owner_invalid"
    );
  }
  return normalizedOwner;
}

function normalizeRuntimeConfigScope(scope = RUNTIME_CONFIG_SCOPES.DEV) {
  const normalizedScope = normalizeText(scope || RUNTIME_CONFIG_SCOPES.DEV);
  if (!RUNTIME_CONFIG_SCOPE_VALUES.has(normalizedScope)) {
    throw runtimeConfigError(
      `Invalid runtime config scope: ${normalizedScope || "(empty)"}`,
      "vibe64_runtime_config_scope_invalid"
    );
  }
  return normalizedScope;
}

function normalizeRuntimeConfigPhase(phase = "") {
  const normalizedPhase = normalizeText(phase);
  if (!RUNTIME_CONFIG_PHASE_VALUES.has(normalizedPhase)) {
    throw runtimeConfigError(
      `Invalid runtime config phase: ${normalizedPhase || "(empty)"}`,
      "vibe64_runtime_config_phase_invalid"
    );
  }
  return normalizedPhase;
}

function normalizeRuntimeConfigPhases(phases = []) {
  return [...new Set((Array.isArray(phases) ? phases : [])
    .map(normalizeRuntimeConfigPhase))]
    .sort((left, right) => left.localeCompare(right));
}

function runtimeConfigKeyLooksSecret(key = "") {
  return RUNTIME_CONFIG_SECRET_KEY_PATTERN.test(String(key || ""));
}

function normalizeRuntimeConfigRecord(record = {}) {
  if (!isPlainObject(record)) {
    throw runtimeConfigError("Runtime config records must be objects.", "vibe64_runtime_config_record_invalid");
  }
  const key = normalizeRuntimeConfigKey(record.key);
  const owner = normalizeRuntimeConfigOwner(record.owner);
  const secret = record.secret === undefined
    ? runtimeConfigKeyLooksSecret(key)
    : record.secret === true;
  return {
    editable: record.editable === undefined ? owner === RUNTIME_CONFIG_OWNERS.USER : record.editable === true,
    key,
    materialize: record.materialize !== false,
    owner,
    requiredFor: normalizeRuntimeConfigPhases(record.requiredFor),
    scope: normalizeRuntimeConfigScope(record.scope),
    secret,
    source: normalizeText(record.source),
    value: String(record.value ?? "")
  };
}

function runtimeConfigRecordSort(left, right) {
  return left.scope.localeCompare(right.scope) ||
    left.key.localeCompare(right.key) ||
    left.owner.localeCompare(right.owner) ||
    left.source.localeCompare(right.source);
}

function mergeRuntimeConfigRecords(records = []) {
  const byScopeKey = new Map();
  for (const record of (Array.isArray(records) ? records : [])) {
    const normalizedRecord = normalizeRuntimeConfigRecord(record);
    byScopeKey.set(`${normalizedRecord.scope}\0${normalizedRecord.key}`, normalizedRecord);
  }
  return [...byScopeKey.values()].sort(runtimeConfigRecordSort);
}

function normalizeRuntimeConfigMaterializer(materializer = {}) {
  const format = normalizeText(materializer.format || RUNTIME_CONFIG_DOTENV_FORMAT);
  if (format !== RUNTIME_CONFIG_DOTENV_FORMAT) {
    throw runtimeConfigError(
      `Unsupported runtime config materializer format: ${format || "(empty)"}`,
      "vibe64_runtime_config_materializer_format_invalid"
    );
  }
  const relativePath = normalizeText(materializer.path);
  if (!relativePath || path.isAbsolute(relativePath) || relativePath.split(/[\\/]+/u).includes("..")) {
    throw runtimeConfigError(
      `Invalid runtime config materializer path: ${relativePath || "(empty)"}`,
      "vibe64_runtime_config_materializer_path_invalid"
    );
  }
  return {
    format,
    path: relativePath
  };
}

async function runtimeConfigDefinitions(profile = {}, context = {}) {
  const runtimeProfile = isPlainObject(profile) ? profile : {};
  const definitions = typeof runtimeProfile.definitions === "function"
    ? await runtimeProfile.definitions(context)
    : runtimeProfile.definitions;
  return Array.isArray(definitions) ? definitions : [];
}

async function resolveRuntimeConfig(profile = {}, context = {}) {
  const runtimeProfile = isPlainObject(profile) ? profile : {};
  const adapterId = normalizeText(runtimeProfile.id || context?.adapter?.id);
  const records = mergeRuntimeConfigRecords(await runtimeConfigDefinitions(profile, context));
  const materializers = (Array.isArray(runtimeProfile.materializers) ? runtimeProfile.materializers : [])
    .map(normalizeRuntimeConfigMaterializer);
  const scope = normalizeRuntimeConfigScope(context.scope || RUNTIME_CONFIG_SCOPES.DEV);
  const phases = normalizeRuntimeConfigPhases(Array.isArray(context.phases)
    ? context.phases
    : context.phase
      ? [context.phase]
      : []);
  const missing = missingRuntimeConfigRecords(records, {
    phases,
    scope
  });
  return {
    adapterId,
    materializers,
    missing,
    ok: missing.length === 0,
    phases,
    records,
    scope,
    values: runtimeConfigEnv(records, {
      scope
    }),
    view: runtimeConfigViewModel({
      materializers,
      missing,
      records,
      scope
    })
  };
}

function runtimeConfigRecordsForScope(records = [], scope = RUNTIME_CONFIG_SCOPES.DEV) {
  const normalizedScope = normalizeRuntimeConfigScope(scope);
  return mergeRuntimeConfigRecords(records)
    .filter((record) => record.scope === normalizedScope);
}

function runtimeConfigEnv(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  return Object.fromEntries(runtimeConfigRecordsForScope(records, scope)
    .map((record) => [record.key, record.value]));
}

function missingRuntimeConfigRecords(records = [], {
  phases = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const requiredPhases = new Set(normalizeRuntimeConfigPhases(phases));
  return runtimeConfigRecordsForScope(records, scope)
    .filter((record) => {
      if (record.requiredFor.length === 0) {
        return false;
      }
      if (requiredPhases.size > 0 && !record.requiredFor.some((phase) => requiredPhases.has(phase))) {
        return false;
      }
      return record.value.length === 0;
    })
    .map((record) => ({
      key: record.key,
      owner: record.owner,
      requiredFor: record.requiredFor,
      scope: record.scope,
      source: record.source
    }))
    .sort((left, right) => left.key.localeCompare(right.key));
}

function redactRuntimeConfigValue(record = {}) {
  return record.secret ? REDACTED_RUNTIME_CONFIG_VALUE : record.value;
}

function runtimeConfigViewModel({
  materializers = [],
  missing = [],
  records = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const missingKeys = new Set((Array.isArray(missing) ? missing : []).map((entry) => entry.key));
  return {
    generatedTargets: materializers.map((materializer) => materializer.path),
    records: runtimeConfigRecordsForScope(records, scope).map((record) => ({
      editable: record.editable,
      key: record.key,
      materialize: record.materialize,
      missing: missingKeys.has(record.key),
      owner: record.owner,
      requiredFor: record.requiredFor,
      scope: record.scope,
      secret: record.secret,
      source: record.source,
      value: redactRuntimeConfigValue(record),
      valuePresent: record.value.length > 0
    })),
    scope
  };
}

function generatedRuntimeConfigHeaderPresent(text = "") {
  return String(text || "").startsWith(VIBE64_GENERATED_ENV_HEADER);
}

function dotenvValue(value = "") {
  const text = String(value ?? "");
  if (text === "") {
    return "";
  }
  if (/^[A-Za-z0-9_./:@+-]+$/u.test(text)) {
    return text;
  }
  return JSON.stringify(text);
}

function runtimeConfigRecordsForDotenv(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  return runtimeConfigRecordsForScope(records, scope)
    .filter((record) => record.materialize)
    .sort((left, right) => left.key.localeCompare(right.key));
}

function dotenvText(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const lines = runtimeConfigRecordsForDotenv(records, {
    scope
  })
    .map((record) => `${record.key}=${dotenvValue(record.value)}`);
  return `${VIBE64_GENERATED_ENV_HEADER}\n${lines.join("\n")}${lines.length ? "\n" : ""}`;
}

function backupTimestamp(date = new Date()) {
  return date.toISOString().replace(/[:.]/gu, "-");
}

async function readOptionalFile(filePath = "") {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (isMissingPathError(error)) {
      return null;
    }
    throw error;
  }
}

async function backupUnmanagedRuntimeConfigFile(filePath = "", {
  now = new Date()
} = {}) {
  const basePath = `${filePath}.vibe64-backup-${backupTimestamp(now)}`;
  let backupPath = basePath;
  let counter = 2;
  while (await pathExists(backupPath)) {
    backupPath = `${basePath}-${counter}`;
    counter += 1;
  }
  await rename(filePath, backupPath);
  return backupPath;
}

async function writeRuntimeConfigDotenvFile(filePath = "", records = [], {
  now = new Date(),
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const existingText = await readOptionalFile(filePath);
  const backupPath = existingText !== null && !generatedRuntimeConfigHeaderPresent(existingText)
    ? await backupUnmanagedRuntimeConfigFile(filePath, {
        now
      })
    : "";
  const materializedRecords = runtimeConfigRecordsForDotenv(records, {
    scope
  });
  const hasSecrets = materializedRecords.some((record) => record.secret);
  await mkdir(path.dirname(filePath), {
    recursive: true
  });
  await writeFile(filePath, dotenvText(records, {
    scope
  }), {
    mode: hasSecrets ? 0o600 : 0o644
  });
  await chmod(filePath, hasSecrets ? 0o600 : 0o644);
  return {
    backupPath,
    generated: true,
    path: filePath
  };
}

async function materializeRuntimeConfig(config = {}, {
  roots = [],
  scope = config.scope || RUNTIME_CONFIG_SCOPES.DEV,
  now = new Date()
} = {}) {
  const resolvedRoots = [...new Set((Array.isArray(roots) ? roots : [])
    .map((root) => normalizeText(root))
    .filter(Boolean)
    .map((root) => path.resolve(root)))];
  const materializers = Array.isArray(config.materializers) ? config.materializers : [];
  const results = [];
  for (const root of resolvedRoots) {
    for (const materializer of materializers) {
      const normalizedMaterializer = normalizeRuntimeConfigMaterializer(materializer);
      const targetPath = path.join(root, normalizedMaterializer.path);
      if (normalizedMaterializer.format === RUNTIME_CONFIG_DOTENV_FORMAT) {
        results.push(await writeRuntimeConfigDotenvFile(targetPath, config.records, {
          now,
          scope
        }));
      }
    }
  }
  return results;
}

export {
  REDACTED_RUNTIME_CONFIG_VALUE,
  RUNTIME_CONFIG_OWNERS,
  RUNTIME_CONFIG_PHASES,
  RUNTIME_CONFIG_SCOPES,
  VIBE64_GENERATED_ENV_HEADER,
  backupUnmanagedRuntimeConfigFile,
  dotenvText,
  generatedRuntimeConfigHeaderPresent,
  materializeRuntimeConfig,
  mergeRuntimeConfigRecords,
  missingRuntimeConfigRecords,
  normalizeRuntimeConfigRecord,
  resolveRuntimeConfig,
  runtimeConfigEnv,
  runtimeConfigKeyLooksSecret,
  runtimeConfigRecordsForScope,
  runtimeConfigViewModel,
  writeRuntimeConfigDotenvFile
};
