import { chmod, mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  isMissingPathError,
  isPlainObject,
  normalizeText,
  pathExists,
  vibe64Error
} from "./core.js";

const RUNTIME_CONFIG_OWNERS = Object.freeze({
  ADAPTER: "adapter",
  USER: "user",
  VIBE64: "vibe64"
});
const RUNTIME_CONFIG_SCOPES = Object.freeze({
  DEV: "dev",
  PROD: "prod"
});
const RUNTIME_CONFIG_PHASES = Object.freeze({
  CLIENT_BUILD: "client-build",
  DEPLOY: "deploy",
  GENERATE: "generate",
  INSTALL: "install",
  MIGRATE: "migrate",
  PREVIEW: "preview",
  SEED: "seed",
  SERVER: "server"
});
const RUNTIME_CONFIG_TARGETS = Object.freeze({
  CHECKS: "checks",
  COMMAND: "command",
  ENV_FILE: "env-file",
  LAUNCH_TARGET: "launch-target",
  SERVER: "server"
});
const RUNTIME_CONFIG_OWNER_VALUES = new Set(Object.values(RUNTIME_CONFIG_OWNERS));
const RUNTIME_CONFIG_SCOPE_VALUES = new Set(Object.values(RUNTIME_CONFIG_SCOPES));
const RUNTIME_CONFIG_PHASE_VALUES = new Set(Object.values(RUNTIME_CONFIG_PHASES));
const RUNTIME_CONFIG_TARGET_VALUES = new Set(Object.values(RUNTIME_CONFIG_TARGETS));
const RUNTIME_CONFIG_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/u;
const RUNTIME_CONFIG_VIBE64_RESERVED_PREFIX = "VIBE64_";
const RUNTIME_CONFIG_SECRET_KEY_PATTERN = /(PASSWORD|PASS|TOKEN|SECRET|KEY|CREDENTIAL|PWD|DATABASE_URL|DSN)/iu;
const RUNTIME_CONFIG_DOTENV_FORMAT = "dotenv";
const VIBE64_GENERATED_ENV_HEADER_LINES = Object.freeze([
  "# Generated by Vibe64.",
  "# Do not edit. Changes will be overwritten.",
  "# Configure user-owned values in Vibe64 Env."
]);
const VIBE64_GENERATED_ENV_HEADER = `${VIBE64_GENERATED_ENV_HEADER_LINES.join("\n")}\n`;
const REDACTED_RUNTIME_CONFIG_VALUE = "********";

function runtimeConfigError(message, code) {
  return vibe64Error(message, code);
}

function normalizeRuntimeConfigKey(key = "") {
  const normalizedKey = normalizeText(key);
  if (!RUNTIME_CONFIG_KEY_PATTERN.test(normalizedKey)) {
    throw runtimeConfigError(
      `Invalid runtime config key: ${normalizedKey || "(empty)"}`,
      "vibe64_runtime_config_key_invalid"
    );
  }
  return normalizedKey;
}

function normalizeRuntimeConfigOwner(owner = RUNTIME_CONFIG_OWNERS.USER) {
  const normalizedOwner = normalizeText(owner || RUNTIME_CONFIG_OWNERS.USER);
  if (!RUNTIME_CONFIG_OWNER_VALUES.has(normalizedOwner)) {
    throw runtimeConfigError(
      `Invalid runtime config owner: ${normalizedOwner || "(empty)"}`,
      "vibe64_runtime_config_owner_invalid"
    );
  }
  return normalizedOwner;
}

function normalizeRuntimeConfigScope(scope = RUNTIME_CONFIG_SCOPES.DEV) {
  const normalizedScope = normalizeText(scope || RUNTIME_CONFIG_SCOPES.DEV);
  if (!RUNTIME_CONFIG_SCOPE_VALUES.has(normalizedScope)) {
    throw runtimeConfigError(
      `Invalid runtime config scope: ${normalizedScope || "(empty)"}`,
      "vibe64_runtime_config_scope_invalid"
    );
  }
  return normalizedScope;
}

function normalizeRuntimeConfigPhase(phase = "") {
  const normalizedPhase = normalizeText(phase);
  if (!RUNTIME_CONFIG_PHASE_VALUES.has(normalizedPhase)) {
    throw runtimeConfigError(
      `Invalid runtime config phase: ${normalizedPhase || "(empty)"}`,
      "vibe64_runtime_config_phase_invalid"
    );
  }
  return normalizedPhase;
}

function normalizeRuntimeConfigPhases(phases = []) {
  return [...new Set((Array.isArray(phases) ? phases : [])
    .map(normalizeRuntimeConfigPhase))]
    .sort((left, right) => left.localeCompare(right));
}

function normalizeRuntimeConfigTarget(target = "") {
  const normalizedTarget = normalizeText(target);
  if (!RUNTIME_CONFIG_TARGET_VALUES.has(normalizedTarget)) {
    throw runtimeConfigError(
      `Invalid runtime config target: ${normalizedTarget || "(empty)"}`,
      "vibe64_runtime_config_target_invalid"
    );
  }
  return normalizedTarget;
}

function normalizeRuntimeConfigTargets(targets = []) {
  return [...new Set((Array.isArray(targets) ? targets : [])
    .map(normalizeRuntimeConfigTarget))]
    .sort((left, right) => left.localeCompare(right));
}

function runtimeConfigKeyLooksSecret(key = "") {
  return RUNTIME_CONFIG_SECRET_KEY_PATTERN.test(String(key || ""));
}

function runtimeConfigKeyIsVibe64Reserved(key = "") {
  return normalizeText(key).startsWith(RUNTIME_CONFIG_VIBE64_RESERVED_PREFIX);
}

function normalizeRuntimeConfigRecord(record = {}) {
  if (!isPlainObject(record)) {
    throw runtimeConfigError("Runtime config records must be objects.", "vibe64_runtime_config_record_invalid");
  }
  const key = normalizeRuntimeConfigKey(record.key);
  const owner = normalizeRuntimeConfigOwner(record.owner);
  const secret = record.secret === undefined
    ? runtimeConfigKeyLooksSecret(key)
    : record.secret === true;
  return {
    editable: record.editable === undefined ? owner === RUNTIME_CONFIG_OWNERS.USER : record.editable === true,
    key,
    materialize: record.materialize !== false,
    owner,
    requiredFor: normalizeRuntimeConfigPhases(record.requiredFor),
    scope: normalizeRuntimeConfigScope(record.scope),
    secret,
    source: normalizeText(record.source),
    targets: normalizeRuntimeConfigTargets(record.targets),
    value: String(record.value ?? ""),
    valuePresent: record.valuePresent === undefined
      ? String(record.value ?? "").length > 0
      : record.valuePresent === true
  };
}

function runtimeConfigRecordSort(left, right) {
  return left.scope.localeCompare(right.scope) ||
    left.key.localeCompare(right.key) ||
    left.owner.localeCompare(right.owner) ||
    left.source.localeCompare(right.source);
}

function mergeRuntimeConfigRecords(records = []) {
  const byScopeKey = new Map();
  for (const record of (Array.isArray(records) ? records : [])) {
    const normalizedRecord = normalizeRuntimeConfigRecord(record);
    const recordKey = `${normalizedRecord.scope}\0${normalizedRecord.key}`;
    const existingRecord = byScopeKey.get(recordKey);
    if (!runtimeConfigRecordCanReplace(existingRecord, normalizedRecord)) {
      continue;
    }
    byScopeKey.set(recordKey, normalizedRecord);
  }
  return [...byScopeKey.values()].sort(runtimeConfigRecordSort);
}

function runtimeConfigRecordCanReplace(existingRecord = null, incomingRecord = {}) {
  if (!existingRecord) {
    return true;
  }
  if (incomingRecord.owner === RUNTIME_CONFIG_OWNERS.USER && existingRecord.owner !== RUNTIME_CONFIG_OWNERS.USER) {
    return false;
  }
  if (incomingRecord.owner === RUNTIME_CONFIG_OWNERS.USER && existingRecord.editable !== true) {
    return false;
  }
  return true;
}

function normalizeRuntimeConfigMaterializer(materializer = {}) {
  const format = normalizeText(materializer.format || RUNTIME_CONFIG_DOTENV_FORMAT);
  if (format !== RUNTIME_CONFIG_DOTENV_FORMAT) {
    throw runtimeConfigError(
      `Unsupported runtime config materializer format: ${format || "(empty)"}`,
      "vibe64_runtime_config_materializer_format_invalid"
    );
  }
  const relativePath = normalizeText(materializer.path);
  if (!relativePath || path.isAbsolute(relativePath) || relativePath.split(/[\\/]+/u).includes("..")) {
    throw runtimeConfigError(
      `Invalid runtime config materializer path: ${relativePath || "(empty)"}`,
      "vibe64_runtime_config_materializer_path_invalid"
    );
  }
  return {
    format,
    path: relativePath
  };
}

async function runtimeConfigDefinitions(profile = {}, context = {}) {
  const runtimeProfile = isPlainObject(profile) ? profile : {};
  const definitions = typeof runtimeProfile.definitions === "function"
    ? await runtimeProfile.definitions(context)
    : runtimeProfile.definitions;
  return Array.isArray(definitions) ? definitions : [];
}

function normalizeRuntimeConfigKeySet(keys = []) {
  return [...new Set((Array.isArray(keys) ? keys : [])
    .map(normalizeRuntimeConfigKey))]
    .sort((left, right) => left.localeCompare(right));
}

async function resolveRuntimeConfig(profile = {}, context = {}) {
  const runtimeProfile = isPlainObject(profile) ? profile : {};
  const adapterId = normalizeText(runtimeProfile.id || context?.adapter?.id);
  const publicEnvPrefixes = normalizePublicEnvPrefixes(runtimeProfile.publicEnvPrefixes);
  const userValueReservedKeys = normalizeRuntimeConfigKeySet(runtimeProfile.userValueReservedKeys);
  const records = mergeRuntimeConfigRecords([
    ...await runtimeConfigDefinitions(profile, context),
    ...runtimeConfigContextRecords(context)
  ]);
  const materializers = (Array.isArray(runtimeProfile.materializers) ? runtimeProfile.materializers : [])
    .map(normalizeRuntimeConfigMaterializer);
  const scope = normalizeRuntimeConfigScope(context.scope || RUNTIME_CONFIG_SCOPES.DEV);
  const phases = normalizeRuntimeConfigPhases(Array.isArray(context.phases)
    ? context.phases
    : context.phase
      ? [context.phase]
      : []);
  const target = normalizeText(context.target);
  const missing = missingRuntimeConfigRecords(records, {
    phases,
    scope,
    target
  });
  return {
    adapterId,
    materializers,
    missing,
    ok: missing.length === 0,
    phases,
    publicEnvPrefixes,
    records,
    scope,
    target,
    userValueReservedKeys,
    values: runtimeConfigEnv(records, {
      scope,
      target
    }),
    view: runtimeConfigViewModel({
      materializers,
      missing,
      records,
      scope,
      target
    })
  };
}

function normalizePublicEnvPrefixes(prefixes = []) {
  return [...new Set((Array.isArray(prefixes) ? prefixes : [])
    .map((prefix) => normalizeText(prefix))
    .filter(Boolean))]
    .sort((left, right) => left.localeCompare(right));
}

function runtimeConfigKeyIsPublic(key = "", publicEnvPrefixes = []) {
  const normalizedKey = normalizeRuntimeConfigKey(key);
  return normalizePublicEnvPrefixes(publicEnvPrefixes)
    .some((prefix) => normalizedKey.startsWith(prefix));
}

function runtimeConfigContextRecords(context = {}) {
  if (!isPlainObject(context)) {
    return [];
  }
  if (Array.isArray(context.records)) {
    return context.records;
  }
  if (Array.isArray(context.extraRecords)) {
    return context.extraRecords;
  }
  return [];
}

function runtimeConfigRecordMatchesTarget(record = {}, target = "") {
  const normalizedTarget = normalizeText(target);
  if (!normalizedTarget) {
    return true;
  }
  const targets = Array.isArray(record.targets) ? record.targets : [];
  return targets.length === 0 || targets.includes(normalizedTarget);
}

function runtimeConfigRecordsForScope(records = [], scope = RUNTIME_CONFIG_SCOPES.DEV, {
  target = ""
} = {}) {
  const normalizedScope = normalizeRuntimeConfigScope(scope);
  return mergeRuntimeConfigRecords(records)
    .filter((record) => (
      record.scope === normalizedScope &&
      runtimeConfigRecordMatchesTarget(record, target)
    ));
}

function runtimeConfigEnv(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV,
  target = ""
} = {}) {
  return Object.fromEntries(runtimeConfigRecordsForScope(records, scope, {
    target
  })
    .map((record) => [record.key, record.value]));
}

function missingRuntimeConfigRecords(records = [], {
  phases = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV,
  target = ""
} = {}) {
  const requiredPhases = new Set(normalizeRuntimeConfigPhases(phases));
  if (requiredPhases.size === 0) {
    return [];
  }
  return runtimeConfigRecordsForScope(records, scope, {
    target
  })
    .filter((record) => {
      if (record.requiredFor.length === 0) {
        return false;
      }
      if (!record.requiredFor.some((phase) => requiredPhases.has(phase))) {
        return false;
      }
      return record.valuePresent !== true;
    })
    .map((record) => ({
      key: record.key,
      owner: record.owner,
      requiredFor: record.requiredFor,
      scope: record.scope,
      source: record.source
    }))
    .sort((left, right) => left.key.localeCompare(right.key));
}

function redactRuntimeConfigValue(record = {}) {
  return record.secret ? REDACTED_RUNTIME_CONFIG_VALUE : record.value;
}

function runtimeConfigViewRecord(record = {}, {
  missingKeys = new Set()
} = {}) {
  const normalizedRecord = normalizeRuntimeConfigRecord(record);
  return {
    editable: normalizedRecord.editable,
    key: normalizedRecord.key,
    materialize: normalizedRecord.materialize,
    missing: missingKeys.has(normalizedRecord.key),
    owner: normalizedRecord.owner,
    requiredFor: normalizedRecord.requiredFor,
    scope: normalizedRecord.scope,
    secret: normalizedRecord.secret,
    source: normalizedRecord.source,
    value: redactRuntimeConfigValue(normalizedRecord),
    valuePresent: normalizedRecord.valuePresent === true
  };
}

function runtimeConfigEnvViewModel(config = {}) {
  const scope = normalizeRuntimeConfigScope(config.scope || RUNTIME_CONFIG_SCOPES.DEV);
  const view = config.view && typeof config.view === "object" && !Array.isArray(config.view)
    ? config.view
    : runtimeConfigViewModel({
        materializers: config.materializers,
        missing: config.missing,
        records: config.records,
        scope,
        target: normalizeText(config.target)
      });
  return {
    adapterId: normalizeText(config.adapterId),
    environment: scope,
    generatedTargets: view.generatedTargets || [],
    publicEnvPrefixes: normalizePublicEnvPrefixes(config.publicEnvPrefixes),
    records: Array.isArray(view.records) ? view.records : [],
    unavailable: config.unavailable || null
  };
}

function runtimeConfigViewModel({
  materializers = [],
  missing = [],
  records = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV,
  target = ""
} = {}) {
  const missingKeys = new Set((Array.isArray(missing) ? missing : []).map((entry) => entry.key));
  return {
    generatedTargets: materializers.map((materializer) => materializer.path),
    records: runtimeConfigRecordsForScope(records, scope, {
      target
    })
      .map((record) => runtimeConfigViewRecord(record, {
        missingKeys
      })),
    scope
  };
}

function generatedRuntimeConfigHeaderPresent(text = "") {
  return String(text || "").startsWith(VIBE64_GENERATED_ENV_HEADER);
}

function parseRuntimeConfigDotenv(text = "") {
  return String(text || "")
    .split(/\r?\n/u)
    .map(parseRuntimeConfigDotenvLine)
    .filter(Boolean);
}

function parseRuntimeConfigDotenvLine(line = "") {
  const trimmedLine = String(line || "").trim();
  if (!trimmedLine || trimmedLine.startsWith("#")) {
    return null;
  }
  const assignment = trimmedLine.startsWith("export ")
    ? trimmedLine.slice("export ".length).trimStart()
    : trimmedLine;
  const separatorIndex = assignment.indexOf("=");
  if (separatorIndex < 1) {
    return null;
  }
  let key;
  try {
    key = normalizeRuntimeConfigKey(assignment.slice(0, separatorIndex).trim());
  } catch {
    return null;
  }
  return {
    key,
    value: parseRuntimeConfigDotenvValue(assignment.slice(separatorIndex + 1).trim())
  };
}

function parseRuntimeConfigDotenvValue(value = "") {
  const text = String(value ?? "");
  if (text.length >= 2 && text.startsWith("\"") && text.endsWith("\"")) {
    try {
      return JSON.parse(text);
    } catch {
      return text.slice(1, -1);
    }
  }
  if (
    text.length >= 2 &&
    (
      (text.startsWith("'") && text.endsWith("'")) ||
      (text.startsWith("`") && text.endsWith("`"))
    )
  ) {
    return text.slice(1, -1);
  }
  return text;
}

function generatedRuntimeConfigDotenvUserValues(text = "", records = [], {
  publicEnvPrefixes = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV,
  userValueReservedKeys = []
} = {}) {
  const dotenvTextValue = String(text || "");
  if (!generatedRuntimeConfigHeaderPresent(dotenvTextValue)) {
    return {};
  }
  const recordsByKey = new Map(runtimeConfigRecordsForScope(records, scope, {
    target: RUNTIME_CONFIG_TARGETS.ENV_FILE
  })
    .map((record) => [record.key, record]));
  const reservedKeys = new Set(normalizeRuntimeConfigKeySet(userValueReservedKeys));
  const values = {};
  for (const entry of parseRuntimeConfigDotenv(dotenvTextValue.slice(VIBE64_GENERATED_ENV_HEADER.length))) {
    if (runtimeConfigKeyIsVibe64Reserved(entry.key) || reservedKeys.has(entry.key)) {
      continue;
    }
    const existingRecord = recordsByKey.get(entry.key);
    if (existingRecord && !runtimeConfigRecordCanImportDotenvUserValue(existingRecord)) {
      continue;
    }
    values[entry.key] = {
      secret: runtimeConfigKeyIsPublic(entry.key, publicEnvPrefixes) ? false : runtimeConfigKeyLooksSecret(entry.key),
      value: entry.value
    };
  }
  return values;
}

function runtimeConfigRecordCanImportDotenvUserValue(record = {}) {
  if (!record) {
    return true;
  }
  return record.owner === RUNTIME_CONFIG_OWNERS.USER &&
    record.editable === true &&
    record.valuePresent !== true;
}

async function readGeneratedRuntimeConfigDotenvUserValues({
  materializers = [],
  publicEnvPrefixes = [],
  records = [],
  roots = [],
  scope = RUNTIME_CONFIG_SCOPES.DEV,
  userValueReservedKeys = []
} = {}) {
  const values = {};
  const resolvedRoots = [...new Set((Array.isArray(roots) ? roots : [])
    .map((root) => normalizeText(root))
    .filter(Boolean)
    .map((root) => path.resolve(root)))];
  const normalizedMaterializers = (Array.isArray(materializers) ? materializers : [])
    .map(normalizeRuntimeConfigMaterializer);
  for (const root of resolvedRoots) {
    for (const materializer of normalizedMaterializers) {
      if (materializer.format !== RUNTIME_CONFIG_DOTENV_FORMAT) {
        continue;
      }
      const text = await readOptionalFile(path.join(root, materializer.path));
      if (text === null) {
        continue;
      }
      const fileValues = generatedRuntimeConfigDotenvUserValues(text, records, {
        publicEnvPrefixes,
        scope,
        userValueReservedKeys
      });
      for (const [key, value] of Object.entries(fileValues).sort(([left], [right]) => left.localeCompare(right))) {
        if (Object.hasOwn(values, key)) {
          continue;
        }
        values[key] = value;
      }
    }
  }
  return values;
}

function dotenvValue(value = "") {
  const text = String(value ?? "");
  if (text === "") {
    return "";
  }
  if (/^[A-Za-z0-9_./:@+-]+$/u.test(text)) {
    return text;
  }
  return JSON.stringify(text);
}

function runtimeConfigRecordsForDotenv(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  return runtimeConfigRecordsForScope(records, scope, {
    target: RUNTIME_CONFIG_TARGETS.ENV_FILE
  })
    .filter((record) => record.materialize)
    .sort((left, right) => left.key.localeCompare(right.key));
}

function dotenvText(records = [], {
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const lines = runtimeConfigRecordsForDotenv(records, {
    scope
  })
    .map((record) => `${record.key}=${dotenvValue(record.value)}`);
  return `${VIBE64_GENERATED_ENV_HEADER}\n${lines.join("\n")}${lines.length ? "\n" : ""}`;
}

function backupTimestamp(date = new Date()) {
  return date.toISOString().replace(/[:.]/gu, "-");
}

async function readOptionalFile(filePath = "") {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (isMissingPathError(error)) {
      return null;
    }
    throw error;
  }
}

async function fileMode(filePath = "") {
  try {
    return (await stat(filePath)).mode & 0o777;
  } catch (error) {
    if (isMissingPathError(error)) {
      return null;
    }
    throw error;
  }
}

async function backupUnmanagedRuntimeConfigFile(filePath = "", {
  now = new Date()
} = {}) {
  const basePath = `${filePath}.vibe64-backup-${backupTimestamp(now)}`;
  let backupPath = basePath;
  let counter = 2;
  while (await pathExists(backupPath)) {
    backupPath = `${basePath}-${counter}`;
    counter += 1;
  }
  await rename(filePath, backupPath);
  return backupPath;
}

async function writeRuntimeConfigDotenvFile(filePath = "", records = [], {
  now = new Date(),
  scope = RUNTIME_CONFIG_SCOPES.DEV
} = {}) {
  const existingText = await readOptionalFile(filePath);
  const backupPath = existingText !== null && !generatedRuntimeConfigHeaderPresent(existingText)
    ? await backupUnmanagedRuntimeConfigFile(filePath, {
        now
      })
    : "";
  const materializedRecords = runtimeConfigRecordsForDotenv(records, {
    scope
  });
  const hasSecrets = materializedRecords.some((record) => record.secret);
  const expectedText = dotenvText(records, {
    scope
  });
  const expectedMode = hasSecrets ? 0o600 : 0o644;
  if (!backupPath && existingText === expectedText) {
    const existingMode = await fileMode(filePath);
    const modeChanged = existingMode !== null && existingMode !== expectedMode;
    if (modeChanged) {
      await chmod(filePath, expectedMode);
    }
    return {
      backupPath,
      changed: modeChanged,
      generated: true,
      path: filePath
    };
  }
  await mkdir(path.dirname(filePath), {
    recursive: true
  });
  await writeFile(filePath, expectedText, {
    mode: expectedMode
  });
  await chmod(filePath, expectedMode);
  return {
    backupPath,
    changed: true,
    generated: true,
    path: filePath
  };
}

async function materializeRuntimeConfig(config = {}, {
  roots = [],
  scope = config.scope || RUNTIME_CONFIG_SCOPES.DEV,
  now = new Date()
} = {}) {
  const resolvedRoots = [...new Set((Array.isArray(roots) ? roots : [])
    .map((root) => normalizeText(root))
    .filter(Boolean)
    .map((root) => path.resolve(root)))];
  const materializers = Array.isArray(config.materializers) ? config.materializers : [];
  const results = [];
  for (const root of resolvedRoots) {
    for (const materializer of materializers) {
      const normalizedMaterializer = normalizeRuntimeConfigMaterializer(materializer);
      const targetPath = path.join(root, normalizedMaterializer.path);
      if (normalizedMaterializer.format === RUNTIME_CONFIG_DOTENV_FORMAT) {
        results.push(await writeRuntimeConfigDotenvFile(targetPath, config.records, {
          now,
          scope
        }));
      }
    }
  }
  return results;
}

export {
  REDACTED_RUNTIME_CONFIG_VALUE,
  RUNTIME_CONFIG_OWNERS,
  RUNTIME_CONFIG_PHASES,
  RUNTIME_CONFIG_SCOPES,
  RUNTIME_CONFIG_TARGETS,
  VIBE64_GENERATED_ENV_HEADER,
  backupUnmanagedRuntimeConfigFile,
  dotenvText,
  generatedRuntimeConfigDotenvUserValues,
  generatedRuntimeConfigHeaderPresent,
  materializeRuntimeConfig,
  mergeRuntimeConfigRecords,
  missingRuntimeConfigRecords,
  normalizePublicEnvPrefixes,
  normalizeRuntimeConfigKey,
  normalizeRuntimeConfigPhase,
  normalizeRuntimeConfigPhases,
  normalizeRuntimeConfigRecord,
  normalizeRuntimeConfigScope,
  normalizeRuntimeConfigTarget,
  normalizeRuntimeConfigTargets,
  parseRuntimeConfigDotenv,
  readGeneratedRuntimeConfigDotenvUserValues,
  resolveRuntimeConfig,
  runtimeConfigEnv,
  runtimeConfigEnvViewModel,
  runtimeConfigKeyIsVibe64Reserved,
  runtimeConfigKeyLooksSecret,
  runtimeConfigKeyIsPublic,
  runtimeConfigRecordsForScope,
  runtimeConfigViewRecord,
  runtimeConfigViewModel,
  writeRuntimeConfigDotenvFile
};
