const VINEXT_PROJECT_KNOWLEDGE_RELATIVE_PATH = ".vibe64/project-knowledge/vinext.md";
const VINEXT_REVIEW_MODE_CONFIG = "vinext_review_mode";

export {
  VINEXT_PROJECT_KNOWLEDGE_RELATIVE_PATH,
  VINEXT_REVIEW_MODE_CONFIG
};
