const AI_STUDIO_RUNTIME_NAME = "ai-studio";

const AI_STUDIO_APP_ROOT_ENV = "AI_STUDIO_APP_ROOT";
const AI_STUDIO_BYPASS_LOCALHOST_CHECK_ENV = "AI_STUDIO_BYPASS_LOCALHOST_CHECK";
const AI_STUDIO_SKIP_STALE_TERMINAL_CLEANUP_ENV = "AI_STUDIO_SKIP_STALE_TERMINAL_CLEANUP";
const AI_STUDIO_TARGET_ROOT_ENV = "AI_STUDIO_TARGET_ROOT";
const STUDIO_BASE_TOOLCHAIN_IMAGE = `${AI_STUDIO_RUNTIME_NAME}-base-toolchain:0.1.0`;
const STUDIO_PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright";
const STUDIO_PLAYWRIGHT_BROWSERS_VOLUME = "ai_studio_playwright_browsers";
const STUDIO_TOOL_HOME_VOLUME = "ai_studio_tool_home";
const STUDIO_TOOL_HOME_PATH = "/home/studio";
const STUDIO_TOOL_HOME_NPM_PREFIX = `${STUDIO_TOOL_HOME_PATH}/.local`;
const STUDIO_TOOL_HOME_BIN_PATH = `${STUDIO_TOOL_HOME_NPM_PREFIX}/bin`;
const STUDIO_TEMP_DIR_NAME = AI_STUDIO_RUNTIME_NAME;

const STUDIO_DOCKER_LABEL_PREFIX = AI_STUDIO_RUNTIME_NAME;
const STUDIO_DAEMON_PID_LABEL = `${STUDIO_DOCKER_LABEL_PREFIX}.daemon-pid`;

const STUDIO_HOST_UID_ENV = "AI_STUDIO_HOST_UID";
const STUDIO_HOST_GID_ENV = "AI_STUDIO_HOST_GID";

const STUDIO_CODEX_CONTAINER_PREFIX = `${AI_STUDIO_RUNTIME_NAME}-codex`;

function studioDockerLabel(name = "", value = undefined) {
  const key = `${STUDIO_DOCKER_LABEL_PREFIX}.${String(name || "").trim()}`;
  return value === undefined ? key : `${key}=${String(value)}`;
}

export {
  AI_STUDIO_APP_ROOT_ENV,
  AI_STUDIO_BYPASS_LOCALHOST_CHECK_ENV,
  AI_STUDIO_RUNTIME_NAME,
  AI_STUDIO_SKIP_STALE_TERMINAL_CLEANUP_ENV,
  AI_STUDIO_TARGET_ROOT_ENV,
  STUDIO_CODEX_CONTAINER_PREFIX,
  STUDIO_BASE_TOOLCHAIN_IMAGE,
  STUDIO_DAEMON_PID_LABEL,
  STUDIO_HOST_GID_ENV,
  STUDIO_HOST_UID_ENV,
  STUDIO_PLAYWRIGHT_BROWSERS_PATH,
  STUDIO_PLAYWRIGHT_BROWSERS_VOLUME,
  STUDIO_TOOL_HOME_BIN_PATH,
  STUDIO_TOOL_HOME_NPM_PREFIX,
  STUDIO_TOOL_HOME_PATH,
  STUDIO_TEMP_DIR_NAME,
  STUDIO_TOOL_HOME_VOLUME,
  studioDockerLabel
};
