/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/dashboard'
      | '/home/dashboard/accounts/'
      | '/home/dashboard/configure/'
      | '/home/dashboard/history/'
      | '/home/dashboard/remote/'
      | '/home/dashboard/run/'
      | '/home/dashboard/setup/'
    >,
    '/home/dashboard': RouteRecordInfo<
      '/home/dashboard',
      '/home/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/home/dashboard/accounts/'
      | '/home/dashboard/configure/'
      | '/home/dashboard/history/'
      | '/home/dashboard/remote/'
      | '/home/dashboard/run/'
      | '/home/dashboard/setup/'
    >,
    '/home/dashboard/accounts/': RouteRecordInfo<
      '/home/dashboard/accounts/',
      '/home/dashboard/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/dashboard/configure/': RouteRecordInfo<
      '/home/dashboard/configure/',
      '/home/dashboard/configure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/dashboard/history/': RouteRecordInfo<
      '/home/dashboard/history/',
      '/home/dashboard/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/dashboard/remote/': RouteRecordInfo<
      '/home/dashboard/remote/',
      '/home/dashboard/remote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/dashboard/run/': RouteRecordInfo<
      '/home/dashboard/run/',
      '/home/dashboard/run',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/dashboard/setup/': RouteRecordInfo<
      '/home/dashboard/setup/',
      '/home/dashboard/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
        | '/home/dashboard'
        | '/home/dashboard/accounts/'
        | '/home/dashboard/configure/'
        | '/home/dashboard/history/'
        | '/home/dashboard/remote/'
        | '/home/dashboard/run/'
        | '/home/dashboard/setup/'
      views:
        | 'default'
    }
    'src/pages/home/dashboard.vue': {
      routes:
        | '/home/dashboard'
        | '/home/dashboard/accounts/'
        | '/home/dashboard/configure/'
        | '/home/dashboard/history/'
        | '/home/dashboard/remote/'
        | '/home/dashboard/run/'
        | '/home/dashboard/setup/'
      views:
        | 'default'
    }
    'src/pages/home/dashboard/accounts/index.vue': {
      routes:
        | '/home/dashboard/accounts/'
      views:
        | never
    }
    'src/pages/home/dashboard/configure/index.vue': {
      routes:
        | '/home/dashboard/configure/'
      views:
        | never
    }
    'src/pages/home/dashboard/history/index.vue': {
      routes:
        | '/home/dashboard/history/'
      views:
        | never
    }
    'src/pages/home/dashboard/remote/index.vue': {
      routes:
        | '/home/dashboard/remote/'
      views:
        | never
    }
    'src/pages/home/dashboard/run/index.vue': {
      routes:
        | '/home/dashboard/run/'
      views:
        | never
    }
    'src/pages/home/dashboard/setup/index.vue': {
      routes:
        | '/home/dashboard/setup/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
