/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bootup-setup': RouteRecordInfo<
      '/bootup-setup',
      '/bootup-setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/'
      | '/home/history'
      | '/home/npm-scripts'
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/history': RouteRecordInfo<
      '/home/history',
      '/home/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/npm-scripts': RouteRecordInfo<
      '/home/npm-scripts',
      '/home/npm-scripts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/bootup-setup.vue': {
      routes:
        | '/bootup-setup'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
        | '/home/'
        | '/home/history'
        | '/home/npm-scripts'
      views:
        | 'default'
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/home/history.vue': {
      routes:
        | '/home/history'
      views:
        | never
    }
    'src/pages/home/npm-scripts.vue': {
      routes:
        | '/home/npm-scripts'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
