const HUMAN_INPUT_RESPONSE_ARTIFACT = "response.md";
const ISSUE_BODY_ARTIFACT = "issue.md";
const ISSUE_TITLE_ARTIFACT = "issue_title";
const ISSUE_WORD_ARTIFACT = "issue_word";
const PLAN_SUMMARY_ARTIFACT = "plan-summary.md";
const PLAN_TECHNICAL_ARTIFACT = "plan-technical.md";
const PULL_REQUEST_BODY_DRAFT_ARTIFACT = "tmp/create_and_merge_pull_request.body.md";
const PULL_REQUEST_TITLE_DRAFT_ARTIFACT = "tmp/create_and_merge_pull_request.title.txt";
const REPORT_ARTIFACT = "report.md";
const WORK_BODY_ARTIFACT = "work.md";
const WORK_TITLE_ARTIFACT = "work_title";
const WORK_WORD_ARTIFACT = "work_word";

export {
  HUMAN_INPUT_RESPONSE_ARTIFACT,
  ISSUE_BODY_ARTIFACT,
  ISSUE_TITLE_ARTIFACT,
  ISSUE_WORD_ARTIFACT,
  PLAN_SUMMARY_ARTIFACT,
  PLAN_TECHNICAL_ARTIFACT,
  PULL_REQUEST_BODY_DRAFT_ARTIFACT,
  PULL_REQUEST_TITLE_DRAFT_ARTIFACT,
  REPORT_ARTIFACT,
  WORK_BODY_ARTIFACT,
  WORK_TITLE_ARTIFACT,
  WORK_WORD_ARTIFACT
};
